Update files.py
stevens68/twixtbot-ui pull request #6
Opened 2021-02-28 08:54 UTC by agtoever

Refactored entire module. Added docstrings. Added support for opening tsgf files. Improved error handling.

2021-03-01 21:48 UTC, stevens68 commented on src/files.py
> +        raise ValueError("Can't read player names from T1 file.")
I think we should handle this with a popup withhout reraising (like the case cannot read player names) so the program doesn't crash

2021-03-01 21:49 UTC, stevens68 commented on src/files.py
> +        raise
dito (popup message something like "unknown error in file....")

2021-03-01 21:49 UTC, stevens68 commented on src/files.py
> +        raise ValueError('Found more than 1 line in a tsgf file.')
dito

2021-03-01 21:50 UTC, stevens68 commented on src/files.py
> +        raise ValueError("Can't read player names from tsgf file.")
dito

2021-03-01 21:50 UTC, stevens68 commented on src/files.py
> +        raise
dito

2021-03-01 21:58 UTC, stevens68 requested changes
Hi agtoever
thanks for your contribution!! Well done! I just added one remark (multiple occurences): Would like to keep the program going in case of unreadable files.

I also found a bug (not related to your change): It's not possible to undo the first move of a game. After you try you cannot even reset the board. Will have to look into it.

I meanwhile replaced time.clock in master branch; I think you hit that issue, too.   So did bob440 when trying to run twixtbot-ui on Python 3.8 (ubuntu)

2021-03-03 12:15 UTC, agtoever commented on src/files.py
> +        raise ValueError("Can't read player names from T1 file.")
Agree. I'll catch and handle it in get_game(). I like to focus user interaction to a restricted number of functions.

2021-03-03 12:15 UTC, agtoever commented on src/files.py
> +        raise
Agree. I'll catch and handle it in get_game(). I like to focus user interaction to a restricted number of functions.

2021-03-03 12:17 UTC, agtoever commented on src/files.py
> +        raise ValueError('Found more than 1 line in a tsgf file.')
Agree. I'll catch and handle it in get_game(). I like to focus user interaction to a restricted number of functions.

2021-03-03 12:17 UTC, agtoever commented on src/files.py
> +        raise
Agree. I'll catch and handle it in get_game(). I like to focus user interaction to a restricted number of functions.

2021-03-03 12:37 UTC, agtoever commented on src/files.py
> +        raise ValueError("Can't read player names from tsgf file.")
This is exception is already handled (and does not lead to an application crash)

2021-03-03 12:39 UTC, agtoever commented
Added patch-2 with error handling in get_game(). 
I like to restrict user interaction (such as popups) to a restricted number of functions.
This makes the functions without user interaction much easier to test and maintain.

2021-03-03 22:43 UTC, stevens68 approved these changes
thanks for the changes!

2021-03-03 22:43 UTC, merged